name: Build
on:
  create:
    tag:
      - 0.*
jobs:
  Build:
    runs-on: ubuntu-20.04
    # container: docker:latest
    steps:
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: cr.yandex
          username: ${{ secrets.YCR_LOGIN }}
          password: ${{ secrets.YCR_PASS }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cr.yandex/crp7eheeka3pphv65e5o/commutator:${{ steps.extract_tag.outputs.tag }}