name: Main Pipeline
on:
  create:
    tags:
      - 0.*.*
  push:
    branches:
      - main
      - develop
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Go setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Checkout?
        uses: actions/checkout@v1
      
      - name: Test
        run: make test
